title: Future Engineer
email: hello@example.com # TODO: replace with program email
description: Un programa de fundamentos de ingeniería de 8 semanas para estudiantes de 15 a 18 años.
baseurl: ""
url: ""
application_url: "https://www.diego.com" # TODO: replace with the live application URL

markdown: kramdown
